export const products = [
	{
		sku: '12345',
		imageUrl: '/products/apple.svg',
		name: 'Apple',
		inStock: 15,
		unitType: 'Kg',
		packType: 'Box',
		unitPerPack: 5,
		pricePerPack: 1.57,
		description: '',
		category: 'Fruits',
	},
	{
		sku: '12344',
		imageUrl: '/products/Avocado.svg',
		name: 'Avocado',
		inStock: 20,
		unitType: 'Each',
		packType: 'Box',
		unitPerPack: 10,
		pricePerPack: 1.57,
		description: '',
		category: 'Fruits',
	},
	{
		sku: '12343',
		imageUrl: '/products/Banana.svg',
		name: 'Banana',
		inStock: 36,
		unitType: 'Each',
		packType: 'Bunch',
		unitPerPack: 6,
		pricePerPack: 1.57,
		description: '',
		category: 'Fruits',
	},
	{
		sku: '12342',
		imageUrl: '/products/Beef.svg',
		name: 'Beef',
		inStock: 15,
		unitType: 'Kg',
		packType: 'Box',
		unitPerPack: 5,
		pricePerPack: 1.57,
		description: '',
		category: 'Meat',
	},
	{
		sku: '12341',
		imageUrl: '/products/Bread.svg',
		name: 'Bread',
		inStock: 20,
		unitType: 'Each',
		packType: 'Box',
		unitPerPack: 10,
		pricePerPack: 1.57,
		description: '',
		category: 'Bakery',
	},
	{
		sku: '12340',
		imageUrl: '/products/Chicken.svg',
		name: 'Chicken',
		inStock: 5,
		unitType: 'Kg',
		packType: 'Box',
		unitPerPack: 5,
		pricePerPack: 1.57,
		description: '',
		category: 'Meat',
	},
	{
		sku: '12339',
		imageUrl: '/products/Chocolate.svg',
		name: 'Chocolate',
		inStock: 120,
		unitType: 'Each',
		packType: 'Box',
		unitPerPack: 10,
		pricePerPack: 1.57,
		description: '',
		category: 'Sweets',
	},
	{
		sku: '12338',
		imageUrl: '/products/Coffee.svg',
		name: 'Coffee',
		inStock: 10,
		unitType: 'Kg',
		packType: 'Box',
		unitPerPack: 5,
		pricePerPack: 1.57,
		description: '',
		category: 'Drinks',
	},
	{
		sku: '12337',
		imageUrl: '/products/Milk.svg',
		name: 'Milk',
		inStock: 250,
		unitType: 'Bottle',
		packType: 'Box',
		unitPerPack: 10,
		pricePerPack: 1.57,
		description: '',
		category: 'Drinks',
	},
	{
		sku: '12336',
		imageUrl: '/products/OrangeJuice.svg',
		name: 'Orange juice',
		inStock: 20,
		unitType: 'Bottle',
		packType: 'Box',
		unitPerPack: 10,
		pricePerPack: 1.57,
		description: '',
		category: 'Drinks',
	},
	{
		sku: '12335',
		imageUrl: '/products/Salmon.svg',
		name: 'Salmon',
		inStock: 25,
		unitType: 'Kg',
		packType: 'Box',
		unitPerPack: 5,
		pricePerPack: 1.57,
		description: '',
		category: 'Fish',
	},
	{
		sku: '12334',
		imageUrl: '/products/Tomato.svg',
		name: 'Tomato',
		inStock: 10,
		unitType: 'Kg',
		packType: 'Box',
		unitPerPack: 5,
		pricePerPack: 1.57,
		description: '',
		category: 'Vegetables',
	},
]

export const categories = [
	{ id: 1, name: 'Bakery' },
	{ id: 2, name: 'Drinks' },
	{ id: 3, name: 'Fish' },
	{ id: 4, name: 'Fruits' },
	{ id: 5, name: 'Meat' },
	{ id: 6, name: 'Sweets' },
	{ id: 7, name: 'Vegetables' },
]

export const unitTypes = [
	{ value: 'Kg', label: 'Kg' },
	{ value: 'Each', label: 'Each' },
	{ value: 'Bottle', label: 'Bottle' },
]

export const packTypes = [
	{ value: 'Box', label: 'Box' },
	{ value: 'Bunch', label: 'Bunch' },
]
